In [1]:
# 50 Numpy Methods

In [2]:
import numpy as np


In [4]:
np.arange(20) 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
np.arange(10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
arr=[[1,7,8,4,7],[6,9,3,2,6,1]]
np.ndim(arr)

1

In [12]:
arr=[[1,7,8,4,2,9],[6,9,3,2,6,1],[2,3,5,7,8,9]]
np.shape(arr)

(3, 6)

In [13]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
np.ones(7)

array([1., 1., 1., 1., 1., 1., 1.])

In [15]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [134]:
x= np.arange(20)


In [26]:
x.dtype.name

'int32'

In [28]:
x.itemsize

4

In [29]:
type(x)

numpy.ndarray

In [33]:
np.empty((4,6))

array([[9.79227811e-153, 1.09918048e+155, 2.17159873e+214,
        2.35287091e+251, 3.68779018e+180, 1.10285274e+155],
       [6.01334668e-154, 4.02830956e-090, 2.31650014e-152,
        2.31461563e-152, 1.06209545e+248, 5.00672620e-119],
       [1.47292026e+195, 2.66064805e-260, 1.08365609e+155,
        3.92886754e-027, 5.98737247e+247, 6.05930532e+257],
       [2.34840919e+251, 1.27849494e-152, 1.47142325e+195,
        1.75700681e-152, 6.01347002e-154, 6.01434482e+175]])

In [40]:
np.linspace( 4, 25,8 )
            


array([ 4.,  7., 10., 13., 16., 19., 22., 25.])

In [41]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])

In [133]:
# Find the unique elements of an array.
np.unique([1, 1, 2, 2, 3, 3,4,5,6,6,8])

array([1, 2, 3, 4, 5, 6, 8])

In [43]:
np.logspace(2.0, 3.0, num=4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [44]:
np.geomspace(1, 1000, num=4)


array([   1.,   10.,  100., 1000.])

In [46]:
x = np.arange(9).reshape((3,3))
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [47]:
np.diag(x) #extract diagnal element of array

array([0, 4, 8])

In [53]:
#Create a two-dimensional array with the flattened input as a diagonal.
np.diagflat([[1,2], [2,6]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 6]])

In [57]:
#An array with ones at and below the given diagonal and zeros elsewhere.
np.tri(3, 5, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [59]:
#Interpret the input as a matrix.
x = np.array([[1, 2], [3, 4]])
m = np.asmatrix(x)
print(m)


[[1 2]
 [3 4]]


In [60]:
#Return a contiguous flattened array.
x = np.array([[1, 2, 3], [4, 5, 6]])
np.ravel(x)

array([1, 2, 3, 4, 5, 6])

In [65]:
#Move axes of an array to new positions.while, other axes remain in their original order.
x = np.arange(6,8)
np.moveaxis(x, 0, -1).shape

(2,)

In [74]:
#Interchange two axes of an array.
x = np.array([[1,2,3,4,5,6,7,8,9]])
np.swapaxes(x,0,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [76]:
#Reverse or permute the axes of an array; returns the modified array.
x = np.arange(8).reshape((4,2))
np.transpose(x)

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [78]:
#Convert inputs to arrays with at least one dimension.
x = np.arange(9.0)
np.atleast_1d(x)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [79]:
#View inputs as arrays with at least two dimensions.
x = np.arange(5.0)
np.atleast_2d(x)

array([[0., 1., 2., 3., 4.]])

In [82]:
#Broadcast an array to a new shape.
x = np.array([1, 2, 3])
np.broadcast_to(x, (4, 3))

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [84]:
#Broadcast any number of arrays against each other.
x = np.array([[1,2,3,4,5,6]])
y = np.array([[4],[5]])
np.broadcast_arrays(x, y)

[array([[1, 2, 3, 4, 5, 6],
        [1, 2, 3, 4, 5, 6]]), array([[4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5]])]

In [90]:
#Remove single-dimensional entries from the shape of an array.
x = np.array([[[0], [1], [2], [3], [4]]])
np.squeeze(x).shape

(5,)

In [92]:
#Return an array converted to a float type.
np.asfarray([2,3,4,5,6,7,8,9], dtype='float')

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [95]:
#Convert the input to an array, checking for NaNs or Infs.
a = [1, 2,4,5,6,7,3,8,9]
np.asarray_chkfinite(a, dtype=float)

array([1., 2., 4., 5., 6., 7., 3., 8., 9.])

In [96]:
#Convert an array of size 1 to its scalar equivalent.
np.asscalar(np.array([10]))

10

In [103]:
#Return an ndarray of the provided type that satisfies requirements.
y = np.require(x, dtype=np.float32, requirements=['A', 'O', 'W', 'F'])
y.flags


  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [105]:
#Join a sequence of arrays along an existing axis.
a = np.array([[1,2,3,4], [5,6,7,8]])
b = np.array([[9,10,11,12]])
np.concatenate((a, b))


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [107]:
#Join a sequence of arrays along a new axis.
arrays = [np.random.randn(3, 4) for _ in range(20)]
np.stack(arrays, axis=0).shape

(20, 3, 4)

In [109]:
#Assemble an nd-array from nested lists of blocks.
A = np.eye(2) *4
B = np.eye(3) * 7
np.block([[A,np.zeros((2, 3))],[np.ones((3, 2)), B]])

array([[4., 0., 0., 0., 0.],
       [0., 4., 0., 0., 0.],
       [1., 1., 7., 0., 0.],
       [1., 1., 0., 7., 0.],
       [1., 1., 0., 0., 7.]])

In [114]:
#Stack arrays in sequence vertically (row wise).
a = np.array([[1], [2], [3],[4],[5]])
b = np.array([[2], [3], [4]])
np.vstack((a,b))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [2],
       [3],
       [4]])

In [116]:
#Stack arrays in sequence horizontally (column wise).
a = np.array((1,2,3,4,6))
b = np.array((2,3,4,5,8,9))
np.hstack((a,b))

array([1, 2, 3, 4, 6, 2, 3, 4, 5, 8, 9])

In [118]:
#Stack arrays in sequence depth wise (along third axis).
a = np.array([[1], [2], [3],[4],[5]])
b = np.array([[2], [3], [4],[6],[7]])
np.dstack((a,b))

array([[[1, 2]],

       [[2, 3]],

       [[3, 4]],

       [[4, 6]],

       [[5, 7]]])

In [119]:
#Stack 1-D arrays as columns into a 2-D array.
a = np.array((1,2,3))
b = np.array((2,3,4))
np.column_stack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [122]:
#Split an array into multiple sub-arrays as views into ary.
x = np.arange(16.0)
np.split(x, 4)

[array([0., 1., 2., 3.]),
 array([4., 5., 6., 7.]),
 array([ 8.,  9., 10., 11.]),
 array([12., 13., 14., 15.])]

In [123]:
#Split an array into multiple sub-arrays.
x = np.arange(8.0)
np.array_split(x, 3)

[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7.])]

In [125]:
#Construct an array by repeating A the number of times given by reps.
a = np.array([0, 1, 2,3])
np.tile(a, 4)

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3])

In [127]:
#Repeat elements of an array.
np.repeat(8,9)

array([8, 8, 8, 8, 8, 8, 8, 8, 8])

In [128]:
#Return a new array with sub-arrays along an axis deleted. For a one dimensional array, this returns those entries not returned by arr[obj].
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [129]:
#Insert values along the given axis before the given indices.
a = np.array([[1, 1], [2, 2], [3, 3]])
np.insert(a, 1, 5)

array([1, 5, 1, 2, 2, 3, 3])

In [130]:
#Append values to the end of an array.
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [137]:
#Reverse the order of elements in an array along the given axis.
x= np.arange(8).reshape((2,2,2))
np.flip(x,0)

array([[[4, 5],
        [6, 7]],

       [[0, 1],
        [2, 3]]])